### ISSUE TITLE
DirectionalSprite is redundant

### ISSUE THREAD

**Issue by brittonwolfe** [Brittdog100/SharpPlatformer#1]
The DirectionalSprite class probably doesn't need to exist, and can probably be replaced with an invert canvas effect on Sprite objects via the the Render() method in the Player class. (Microsoft.Graphics.Canvas.Effects.InvertEffect?)

**Comment by Brittdog100** [comment]
Would require work with Transform2DEffect with a [[-1, 0], [0, 1]] transform matrix; the hard part is passing the source.

**Comment by brittonwolfe** [comment]
Transform2DEffect with transform matrix [[-1, 0], [0, 1]]?

**Comment by brittonwolfe** [comment]
Effects suck so I'll just figure them out later.
